image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build
  tags:
    - chabter
  script:
    - docker build -t $CI_REGISTRY_IMAGE .

test_image:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - aws --version
    - eb --version

push_image:
  stage: deploy
  script:
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest