definitions:
  steps:
    - step: &sync-with-github
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:cbytedigital/docker-aws-elastic-beanstalk-cli.git
          - cd docker-aws-elastic-beanstalk-cli.git
          - git push --mirror git@github.com:cbytedigital/docker-aws-eb-cli.git

pipelines:
  branches:
    default:
      - step: *sync-with-github
    main:
      - step: *sync-with-github
      - step:
          name: Build and Push Docker Image
          services:
            - docker
          script:
            - export DOCKER_BUILDKIT=1
            - docker build -t cbytedigital/aws-eb-cli:latest .
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker push cbytedigital/aws-eb-cli:latest
          caches:
            - docker